language: ruby
cache: bundler
rvm:
  - 2.1.2
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
script: bundle exec rspec spec
