language: ruby
rvm:
  - 2.1.2
env:
  - RAILS_ENV=test
before_script:
  - "mysql -e 'create database pop_test;'"
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
